name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.1
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.12.3
  http: ^1.2.2
  flutter_dotenv: ^6.0.0  # Tetap, tapi jika error .env persist, comment sementara
  cached_network_image: ^3.3.0
  dropdown_search: ^6.0.1
  flutter_local_notifications: ^19.4.1
  timezone: 0.10.1
  geolocator: ^14.0.2
  geocoding: ^2.2.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  open_file: ^3.5.9
  share_plus: ^12.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.1
  excel: ^2.0.0-null-safety-3
  intl: ^0.18.0
  mockito: ^5.4.2

  overlay_support: ^2.1.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/icons/  # Pastikan ini ada untuk ikon pohon-hijau.png dll
    - assets/icons/pohon-hijau.png
    - assets/icons/pohon-kuning.png
    - assets/icons/pohon-merah.png
    - assets/icons/report.png
    - assets/icons/home.png
    - assets/icons/peta.png
    - assets/icons/notification.png
    - assets/icons/profile.png
    - assets/icons/setting.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - .env  # Comment ini jika error FileNotFoundError persist; gunakan hardcode sementara
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

          